package com.test.task.exceptions

class UserNotFoundException : ApplicationException("User not found")
